sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAVh9Wgkv9nN4e7Q4nM
    access-key-secret: q0D0jLd3Rg67mNu1N2OU5x1Q5OhDVl
    bucket-name: oos-yang
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wxc94b35056563c117
    secret: e35617779a517974b38766d30684460a